import { useState, useEffect } from "react"
import { useNavigate } from "react-router-dom"
import { saveStyles, getStyles } from "../services/api"
import AppHeader from "../components/AppHeader"
import { ArrowLeft } from "../components/Icons"

const ALL_STYLES = [
  "casual", "streetwear", "formal", "vintage", "minimalista",
  "y2k", "desportivo", "grunge", "preppy", "boho", "chic",
  "techwear", "clássico", "smart-casual", "gótico", "cyberpunk",
  "skater", "business", "romântico", "indie", "artsy", "old-money",
  "loungewear", "retro", "alta-costura", "urbano", "festivo", "verão", "inverno"
]

export default function SettingsStyles() {
  const [selected, setSelected] = useState(new Set())
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [activeTab, setActiveTab] = useState("tinder") // "tinder" ou "manual"
  const navigate = useNavigate()

  useEffect(() => {
    async function load() {
      try {
        const data = await getStyles()
        if (data && data.styleWeights) {
          const weights = JSON.parse(data.styleWeights)
          // Normaliza tudo para minúsculas para não entrar em conflito com o ALL_STYLES
          const tags = Object.keys(weights).map(t => t.toLowerCase().trim())
          setSelected(new Set(tags))
        }
      } catch (err) {
        console.error("Failed to load styles:", err)
      }
    }
    load()
  }, [])

  function toggle(id) {
    setSelected(prev => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  async function handleSave() {
    if (selected.size === 0) {
      setError("Seleciona pelo menos um estilo.")
      return
    }
    setLoading(true)
    setError("")
    try {
      const total = selected.size
      const weights = {}
      selected.forEach(id => { weights[id] = +(1 / total).toFixed(2) })
      await saveStyles(weights, null, null, null)
      navigate("/outfits")
    } catch (err) {
      setError("Não foi possível guardar: " + err.message)
    } finally {
      setLoading(false)
    }
  }

  // Combine default styles with any dynamic styles generated by the AI
  const displayStyles = [...new Set([...ALL_STYLES, ...selected])]

  return (
    <div className="app-container">
      <AppHeader />

      <button className="back-link" onClick={() => navigate(-1)}>
        <ArrowLeft /> Voltar
      </button>

      <div className="page-header">
        <h1 className="page-title">Preferências de estilo</h1>
        <p className="page-subtitle">Ajusta o teu Style DNA como preferires</p>
      </div>

      <div style={{ display: "flex", gap: "10px", marginBottom: "24px" }}>
        <button 
          className={`btn ${activeTab === "tinder" ? "btn-primary" : "btn-secondary"}`}
          style={{ flex: 1 }}
          onClick={() => setActiveTab("tinder")}
        >
          Descoberta Inteligente
        </button>
        <button 
          className={`btn ${activeTab === "manual" ? "btn-primary" : "btn-secondary"}`}
          style={{ flex: 1 }}
          onClick={() => setActiveTab("manual")}
        >
          Menu Manual
        </button>
      </div>

      {activeTab === "tinder" && (
        <div className="preference-section">
          <button 
            className="btn btn-secondary" 
            onClick={() => navigate("/onboarding/styles")}
            style={{ width: "100%", padding: "12px", background: "linear-gradient(135deg, var(--accent) 0%, #d4ff70 100%)", color: "#000", border: "none", fontWeight: "bold", display: "flex", justifyContent: "center", gap: "8px", alignItems: "center", marginBottom: "24px" }}
          >
            <span>🔥</span> Iniciar Descoberta de Estilo
          </button>

          <h3>O teu Style DNA</h3>
          <p className="page-subtitle" style={{ marginBottom: "20px" }}>
            Aqui estão os elementos chave que a IA do Groq identificou no teu estilo com base nas tuas escolhas da Descoberta:
          </p>
          
          {selected.size === 0 ? (
            <p style={{ color: "var(--color-text-muted)", fontStyle: "italic" }}>Ainda não definiste o teu estilo. Faz o teste acima!</p>
          ) : (
            <div style={{ display: "flex", flexWrap: "wrap", gap: "10px" }}>
              {[...selected].map(tag => (
                <div
                  key={tag}
                  className="style-chip selected"
                  style={{ cursor: "default", textTransform: "capitalize", fontSize: "16px", padding: "8px 16px" }}
                >
                  #{tag}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {activeTab === "manual" && (
        <div className="preference-section">
          <h3>Menu Manual de Hashtags</h3>
          <p className="page-subtitle" style={{ marginBottom: "20px" }}>
            Seleciona as tuas vibes favoritas para que o Groq possa gerar os melhores outfits para ti.
          </p>
          
          <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginBottom: "2rem" }}>
            {displayStyles.map(tag => {
              const isSelected = selected.has(tag)
              return (
                <div
                  key={tag}
                  onClick={() => toggle(tag)}
                  className={`style-chip ${isSelected ? "selected" : ""}`}
                  style={{ 
                    cursor: "pointer", 
                    textTransform: "capitalize", 
                    fontSize: "16px", 
                    padding: "8px 16px",
                    transition: "all 0.2s ease"
                  }}
                >
                  #{tag}
                </div>
              )
            })}
          </div>

          {error && <p style={{ color: "var(--color-danger, #ff4a4a)", marginBottom: "1rem" }}>{error}</p>}

          <button 
            className="btn btn-primary" 
            onClick={handleSave} 
            disabled={loading || selected.size === 0}
            style={{ width: "100%" }}
          >
            {loading ? "A guardar..." : "Guardar Preferências Manuais"}
          </button>
        </div>
      )}

    </div>
  )
}
