spring.application.name=codespring-fashion
spring.config.import=optional:file:.env[.properties],optional:file:backend/demo/demo/.env[.properties]

spring.datasource.url=jdbc:h2:file:./data/fashiondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
jwt.expiration=86400000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

groq.api.key=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

app.upload.dir=./uploads

serpapi.key=8947bca3ee0dc87c904de2ce70815e9a543639c86c05b6fe4b683eb7465d2c9e
